import 'package:flutter/material.dart';
import '../../core/safety/audit_logger.dart';
import '../../data/remote/analytics_client.dart';

/// First screen every user sees — legally required AI identity disclosure.
///
/// Compliance: NY GBS Art. 47 (NY-01), CA SB 243 (CA-01).
/// Cannot be skipped. Must be shown before any interaction.
class AiDisclosureScreen extends StatelessWidget {
  final VoidCallback onAccepted;

  const AiDisclosureScreen({super.key, required this.onAccepted});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 24),
          child: Column(
            children: [
              const Spacer(flex: 2),

              // Icon
              Container(
                width: 80,
                height: 80,
                decoration: BoxDecoration(
                  color: theme.colorScheme.primaryContainer,
                  shape: BoxShape.circle,
                ),
                child: Icon(
                  Icons.smart_toy_outlined,
                  size: 40,
                  color: theme.colorScheme.primary,
                ),
              ),
              const SizedBox(height: 32),

              // Title
              Text(
                'Before we begin',
                style: theme.textTheme.headlineSmall?.copyWith(
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 16),

              // Disclosure text
              Container(
                padding: const EdgeInsets.all(20),
                decoration: BoxDecoration(
                  color: theme.colorScheme.surfaceContainerHighest
                      .withValues(alpha: 0.5),
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Column(
                  children: [
                    Text(
                      'Luma is an AI companion — not a human, '
                      'not a real animal, and not a substitute for '
                      'professional help.',
                      style: theme.textTheme.bodyLarge,
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'Your conversations are processed by an AI system. '
                      'Luma has simulated emotions and memory — they feel '
                      'real, but they are generated by software.',
                      style: theme.textTheme.bodyMedium?.copyWith(
                        color: theme.colorScheme.onSurfaceVariant,
                      ),
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'If you are in crisis, please contact the '
                      '988 Suicide & Crisis Lifeline (call or text 988).',
                      style: theme.textTheme.bodyMedium?.copyWith(
                        fontWeight: FontWeight.w600,
                        color: theme.colorScheme.error,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ],
                ),
              ),

              const Spacer(flex: 3),

              // Accept button
              SizedBox(
                width: double.infinity,
                height: 56,
                child: FilledButton(
                  onPressed: () async {
                    await AuditLogger().logDisclosureShown(
                      location: 'onboarding',
                    );
                    AnalyticsClient.instance
                        .aiDisclosureShown(location: 'onboarding');
                    onAccepted();
                  },
                  child: const Text('I understand'),
                ),
              ),
              const SizedBox(height: 12),
              Text(
                'You can review this information anytime in Settings.',
                style: theme.textTheme.bodySmall?.copyWith(
                  color: theme.colorScheme.onSurfaceVariant,
                ),
              ),
              const SizedBox(height: 16),
            ],
          ),
        ),
      ),
    );
  }
}
