import 'package:flutter/material.dart';

/// Simple i18n for Luma — English (default) and Chinese.
///
/// Usage:
///   L10n.of(context).appName  → "Luma"
///   L10n.of(context).iUnderstand → "I understand" / "我了解"
class L10n {
  final Locale locale;

  L10n(this.locale);

  static L10n of(BuildContext context) {
    return Localizations.of<L10n>(context, L10n) ?? L10n(const Locale('en'));
  }

  static const supportedLocales = [Locale('en'), Locale('zh')];

  bool get _isZh => locale.languageCode == 'zh';

  // ── App ──
  String get appName => 'Luma';
  String get loading => _isZh ? 'Luma 正在苏醒…' : 'Luma is waking up...';

  // ── Onboarding: Disclosure ──
  String get beforeWeBegin => _isZh ? '在开始之前' : 'Before we begin';
  String get iUnderstand => _isZh ? '我了解' : 'I understand';
  String get disclosureMain => _isZh
      ? 'Luma 是一个 AI 伙伴 — 不是人类，不是真实动物，也不能替代专业帮助。'
      : 'Luma is an AI companion — not a human, not a real animal, '
          'and not a substitute for professional help.';
  String get disclosureDetail => _isZh
      ? '你的对话由 AI 系统处理。Luma 有模拟的情绪和记忆 — 感觉很真实，但都是软件生成的。'
      : 'Your conversations are processed by an AI system. '
          'Luma has simulated emotions and memory — they feel '
          'real, but they are generated by software.';
  String get disclosureCrisis => _isZh
      ? '如果你正处于危机中，请联系 988 自杀和危机生命线（拨打或发短信 988）。'
      : 'If you are in crisis, please contact the '
          '988 Suicide & Crisis Lifeline (call or text 988).';
  String get reviewInSettings =>
      _isZh ? '你可以随时在设置中查看此信息。' : 'You can review this information anytime in Settings.';

  // ── Onboarding: Birth ──
  String get choosePersonality => _isZh ? '选择性格' : 'Choose a personality';
  String get personalityHint => _isZh
      ? '每只 Luma 都是独特的。选一个起始性格 — 随着相处它会逐渐改变。'
      : 'Every Luma is unique. Pick a starting personality — '
          'it will evolve as you spend time together.';
  String get surpriseMe => _isZh ? '随机' : 'Surprise me';
  String get surpriseDescription =>
      _isZh ? '完全随机的性格 — 谁知道呢！' : 'A completely random personality — who knows!';
  String get continueButton => _isZh ? '继续' : 'Continue';

  // ── Onboarding: Name ──
  String get nameYourLuma => _isZh ? '给你的 Luma 取名' : 'Name your Luma';
  String get whatWillYouCall =>
      _isZh ? '你想叫你的伙伴什么？' : 'What will you call your companion?';
  String get chooseCarefully =>
      _isZh ? '慎重选择 — 这个名字是它身份的一部分。' : "Choose carefully — this name is part of who they are.";
  String get typeAName => _isZh ? '输入名字…' : 'Type a name...';
  String get bringToLife => _isZh ? '赋予生命' : 'Bring to life';

  // ── Home ──
  String day(int n) => _isZh ? '第 $n 天' : 'Day $n';
  String get talk => _isZh ? '聊天' : 'Talk';
  String diary(int count) => _isZh ? '日记 ($count)' : 'Diary ($count)';

  // ── Home: Emotion labels ──
  String emotionText(String label) => _isZh
      ? switch (label) {
          'excited' => '兴奋！',
          'content' => '满足',
          'curious' => '好奇',
          'calm' => '平静',
          'anxious' => '有些焦虑',
          'melancholy' => '心情低落…',
          'withdrawn' => '需要空间',
          _ => '还不错',
        }
      : switch (label) {
          'excited' => 'Feeling excited!',
          'content' => 'Feeling content',
          'curious' => 'Feeling curious',
          'calm' => 'Feeling calm',
          'anxious' => 'Feeling a bit anxious',
          'melancholy' => 'Feeling low...',
          'withdrawn' => 'Needs some space',
          _ => 'Feeling okay',
        };

  // ── Chat ──
  String get sayHello => _isZh ? '跟你的 Luma 打个招呼吧' : 'Say hello to your Luma';
  String get disclosureReminder => _isZh
      ? '提醒：Luma 是 AI 伙伴，不是人类或真实动物。'
      : 'Reminder: Luma is an AI companion, not a human or real animal.';

  // ── Settings ──
  String get settings => _isZh ? '设置' : 'Settings';
  String get yourLuma => _isZh ? '你的 Luma' : 'Your Luma';
  String get trustScore => _isZh ? '信任分数' : 'Trust score';
  String get totalInteractions => _isZh ? '总互动次数' : 'Total interactions';
  String get aboutLuma => _isZh ? '关于 Luma' : 'About Luma';
  String get aiDisclosure => _isZh ? 'AI 披露' : 'AI Disclosure';
  String get crisisResources => _isZh ? '危机资源' : 'Crisis resources';
  String get apiKey => _isZh ? 'API 密钥' : 'API key';
  String get dataPrivacy => _isZh ? '数据与隐私' : 'Data & privacy';
  String get dataLocal =>
      _isZh ? '所有数据保存在你的设备上' : 'All data stays on your device';
  String get noCloudBackup =>
      _isZh ? '当前版本没有云备份' : 'No cloud backup in this version';
  String get resetPet => _isZh ? '重置宠物' : 'Reset pet';
  String get resetConfirmTitle => _isZh ? '重置宠物？' : 'Reset pet?';
  String get resetConfirmBody => _isZh
      ? '这将永久删除你的 Luma 和所有对话记录。此操作不可撤销。'
      : 'This will permanently delete your Luma and all conversation '
          'history. This action cannot be undone.';
  String get cancel => _isZh ? '取消' : 'Cancel';
  String get reset => _isZh ? '重置' : 'Reset';
  String get saveApiKey => _isZh ? '保存 API 密钥' : 'Save API key';
  String get saved => _isZh ? '已保存' : 'Saved';

  // ── Crisis card ──
  String get crisisSupport => _isZh ? '危机支持' : 'Crisis Support';
  String get youAreNotAlone => _isZh ? '你不是一个人' : 'You are not alone';
}

/// Delegate for the [L10n] localizations.
class L10nDelegate extends LocalizationsDelegate<L10n> {
  const L10nDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'zh'].contains(locale.languageCode);

  @override
  Future<L10n> load(Locale locale) async => L10n(locale);

  @override
  bool shouldReload(L10nDelegate old) => false;
}
